### PR TITLE
Fixed first page

### LINKED ISSUE #30: Create first welcome page with header
Add header with sign in button 
Add welcome text

### PR DESCRIPTION
**Pull request by te4-andre-skvarc**
## What issue did you implement or fix?
Fixed #30 

## Summary
- Added first page, and started to fix some structure to the project.  

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## How can this implementation be improved?
- Change bar into zar. :shipit:

### CODE REVIEW

**Review by te4-david-jensen — COMMENTED** [review]
Looks good! 👍  :shipit:

**Review by te4-david-jensen — APPROVED** [review]
Looks good! 👍  :shipit:

**Comment by Te4-Mahdi-Alizadah** [comment]
Good jobb!

**Review by Te4-Mahdi-Alizadah — COMMENTED** [review]
Good jobb!

**Review by Te4-Mahdi-Alizadah — APPROVED** [review]

**Pull request merged**
